/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class About1 extends javax.swing.JFrame {

    /**
     * Creates new form About1
     */
    public About1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        dashboardBox = new javax.swing.JPanel();
        dash = new javax.swing.JLabel();
        indicator2 = new javax.swing.JPanel();
        financesBox = new javax.swing.JPanel();
        fina = new javax.swing.JLabel();
        indicator3 = new javax.swing.JPanel();
        homemateBox = new javax.swing.JPanel();
        indicator4 = new javax.swing.JPanel();
        Log_Out = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        indicator5 = new javax.swing.JPanel();
        aboutBox = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        indicator6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dashboardBox.setBackground(new java.awt.Color(255, 255, 255));
        dashboardBox.setForeground(new java.awt.Color(240, 240, 240));
        dashboardBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardBoxMouseExited(evt);
            }
        });

        dash.setBackground(new java.awt.Color(0, 0, 0));
        dash.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dash.setText("Dashboard");

        indicator2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator2Layout = new javax.swing.GroupLayout(indicator2);
        indicator2.setLayout(indicator2Layout);
        indicator2Layout.setHorizontalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator2Layout.setVerticalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardBoxLayout = new javax.swing.GroupLayout(dashboardBox);
        dashboardBox.setLayout(dashboardBoxLayout);
        dashboardBoxLayout.setHorizontalGroup(
            dashboardBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardBoxLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(dash)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(dashboardBoxLayout.createSequentialGroup()
                .addComponent(indicator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        dashboardBoxLayout.setVerticalGroup(
            dashboardBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dash)
                .addContainerGap())
            .addComponent(indicator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        financesBox.setBackground(new java.awt.Color(255, 255, 255));
        financesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financesBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                financesBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                financesBoxMouseExited(evt);
            }
        });

        fina.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fina.setText("Finances");

        indicator3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout financesBoxLayout = new javax.swing.GroupLayout(financesBox);
        financesBox.setLayout(financesBoxLayout);
        financesBoxLayout.setHorizontalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financesBoxLayout.createSequentialGroup()
                .addComponent(indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fina)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        financesBoxLayout.setVerticalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financesBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fina)
                .addContainerGap())
            .addComponent(indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        homemateBox.setBackground(new java.awt.Color(255, 255, 255));
        homemateBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homemateBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homemateBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homemateBoxMouseExited(evt);
            }
        });

        indicator4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator4Layout = new javax.swing.GroupLayout(indicator4);
        indicator4.setLayout(indicator4Layout);
        indicator4Layout.setHorizontalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator4Layout.setVerticalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout homemateBoxLayout = new javax.swing.GroupLayout(homemateBox);
        homemateBox.setLayout(homemateBoxLayout);
        homemateBoxLayout.setHorizontalGroup(
            homemateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homemateBoxLayout.createSequentialGroup()
                .addComponent(indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homemateBoxLayout.setVerticalGroup(
            homemateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Log_Out.setBackground(java.awt.Color.white);
        Log_Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_OutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Log_OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Log_OutMouseExited(evt);
            }
        });

        report.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        report.setText("Log Out");

        indicator5.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout indicator5Layout = new javax.swing.GroupLayout(indicator5);
        indicator5.setLayout(indicator5Layout);
        indicator5Layout.setHorizontalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator5Layout.setVerticalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Log_OutLayout = new javax.swing.GroupLayout(Log_Out);
        Log_Out.setLayout(Log_OutLayout);
        Log_OutLayout.setHorizontalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_OutLayout.createSequentialGroup()
                .addComponent(indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(report)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Log_OutLayout.setVerticalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Log_OutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(report)
                .addContainerGap())
            .addComponent(indicator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        aboutBox.setBackground(new java.awt.Color(1, 122, 255));
        aboutBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutBoxMouseExited(evt);
            }
        });

        about.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("About Us");

        indicator6.setBackground(new java.awt.Color(0, 97, 204));

        javax.swing.GroupLayout indicator6Layout = new javax.swing.GroupLayout(indicator6);
        indicator6.setLayout(indicator6Layout);
        indicator6Layout.setHorizontalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator6Layout.setVerticalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout aboutBoxLayout = new javax.swing.GroupLayout(aboutBox);
        aboutBox.setLayout(aboutBoxLayout);
        aboutBoxLayout.setHorizontalGroup(
            aboutBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutBoxLayout.createSequentialGroup()
                .addComponent(indicator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(about)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        aboutBoxLayout.setVerticalGroup(
            aboutBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about)
                .addContainerGap())
            .addComponent(indicator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 122, 255));
        jLabel2.setText("About Us");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Developers: Arittra Das & Debopriya Deb Roy");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("Also thanks to Shafayat Jamil");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Github: https://github.com/DDR13GIT/Becholor_Point ");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Bug Report: https://github.com/avishek202/Becholor_Point/issues");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(financesBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homemateBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Log_Out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(financesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homemateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBoxMouseClicked
        Dashboard_admin d = new Dashboard_admin();
        d.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardBoxMouseClicked

    private void dashboardBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBoxMouseEntered
        // TODO add your handling code here:
        indicator2.setBackground(new Color(0, 0, 0));
        dashboardBox.setBackground(new Color(232, 232, 232));
    }//GEN-LAST:event_dashboardBoxMouseEntered

    private void dashboardBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBoxMouseExited
        // TODO add your handling code here:
        indicator2.setBackground(new Color(255, 255, 255));
        dashboardBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardBoxMouseExited

    private void financesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseClicked
        // TODO add your handling code here:
        NewJFrame1 m = new NewJFrame1();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financesBoxMouseClicked

    private void financesBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseEntered
        // TODO add your handling code here:
        indicator3.setBackground(new Color(0, 0, 0));
        financesBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_financesBoxMouseEntered

    private void financesBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseExited
        // TODO add your handling code here:
        indicator3.setBackground(new Color(255, 255, 255));
        financesBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_financesBoxMouseExited

    private void homemateBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homemateBoxMouseClicked
        // TODO add your handling code here:
        homemate h = new homemate();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homemateBoxMouseClicked

    private void homemateBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homemateBoxMouseEntered
        // TODO add your handling code here:
        indicator4.setBackground(new Color(0, 0, 0));
        homemateBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_homemateBoxMouseEntered

    private void homemateBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homemateBoxMouseExited
        // TODO add your handling code here:
        indicator4.setBackground(new Color(255, 255, 255));
        homemateBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_homemateBoxMouseExited

    private void Log_OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseClicked
        JOptionPane.showMessageDialog(null, "Log Out From Your Account!", "Hey", 1);
        signIN.id = null;
        signIN s = new signIN();
        s.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_Log_OutMouseClicked

    private void Log_OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseEntered
        // TODO add your handling code here:
        indicator5.setBackground(new Color(0, 0, 0));
        Log_Out.setBackground(new Color(247, 59, 63));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_Log_OutMouseEntered

    private void Log_OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseExited
        // TODO add your handling code here:
        indicator5.setBackground(new Color(255, 255, 255));
        Log_Out.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Log_OutMouseExited

    private void aboutBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBoxMouseEntered
        // TODO add your handling code here:
        //        indicator6.setBackground(new Color(0, 0, 0));
        //        aboutBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_aboutBoxMouseEntered

    private void aboutBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutBoxMouseExited
        // TODO add your handling code here:
        //        indicator6.setBackground(new Color(255, 255, 255));
        //        aboutBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_aboutBoxMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Log_Out;
    private javax.swing.JLabel about;
    private javax.swing.JPanel aboutBox;
    private javax.swing.JLabel dash;
    private javax.swing.JPanel dashboardBox;
    private javax.swing.JLabel fina;
    private javax.swing.JPanel financesBox;
    private javax.swing.JPanel homemateBox;
    private javax.swing.JPanel indicator2;
    private javax.swing.JPanel indicator3;
    private javax.swing.JPanel indicator4;
    private javax.swing.JPanel indicator5;
    private javax.swing.JPanel indicator6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel report;
    // End of variables declaration//GEN-END:variables
}
