/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;

import java.awt.Color;

/**
 *
 * @author Hello iT
 */
public class Dashboard extends javax.swing.JFrame implements frame{

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hover1 = new javax.swing.JPanel();
        dash = new javax.swing.JLabel();
        indicator2 = new javax.swing.JPanel();
        hover2 = new javax.swing.JPanel();
        fina = new javax.swing.JLabel();
        indicator3 = new javax.swing.JPanel();
        hover3 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        indicator4 = new javax.swing.JPanel();
        hover4 = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        indicator5 = new javax.swing.JPanel();
        hover5 = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        indicator6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel4.setBackground(new java.awt.Color(247, 240, 241));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        hover1.setBackground(new java.awt.Color(1, 122, 255));

        dash.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dash.setForeground(new java.awt.Color(240, 240, 240));
        dash.setText("Dashboard");

        indicator2.setBackground(new java.awt.Color(0, 97, 204));

        javax.swing.GroupLayout indicator2Layout = new javax.swing.GroupLayout(indicator2);
        indicator2.setLayout(indicator2Layout);
        indicator2Layout.setHorizontalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator2Layout.setVerticalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hover1Layout = new javax.swing.GroupLayout(hover1);
        hover1.setLayout(hover1Layout);
        hover1Layout.setHorizontalGroup(
            hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(dash)
                .addGap(0, 129, Short.MAX_VALUE))
            .addGroup(hover1Layout.createSequentialGroup()
                .addComponent(indicator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        hover1Layout.setVerticalGroup(
            hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dash)
                .addContainerGap())
            .addComponent(indicator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hover2.setBackground(new java.awt.Color(255, 255, 255));
        hover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover2MouseExited(evt);
            }
        });

        fina.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fina.setText("Finances");

        indicator3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hover2Layout = new javax.swing.GroupLayout(hover2);
        hover2.setLayout(hover2Layout);
        hover2Layout.setHorizontalGroup(
            hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover2Layout.createSequentialGroup()
                .addComponent(indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fina)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hover2Layout.setVerticalGroup(
            hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fina)
                .addContainerGap())
            .addComponent(indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hover3.setBackground(new java.awt.Color(255, 255, 255));
        hover3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover3MouseExited(evt);
            }
        });

        home.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        home.setText("Homemate");

        indicator4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator4Layout = new javax.swing.GroupLayout(indicator4);
        indicator4.setLayout(indicator4Layout);
        indicator4Layout.setHorizontalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator4Layout.setVerticalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hover3Layout = new javax.swing.GroupLayout(hover3);
        hover3.setLayout(hover3Layout);
        hover3Layout.setHorizontalGroup(
            hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover3Layout.createSequentialGroup()
                .addComponent(indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(home)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hover3Layout.setVerticalGroup(
            hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home)
                .addContainerGap())
            .addComponent(indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hover4.setBackground(new java.awt.Color(255, 255, 255));
        hover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hover4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover4MouseExited(evt);
            }
        });

        report.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        report.setText("Report");

        indicator5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator5Layout = new javax.swing.GroupLayout(indicator5);
        indicator5.setLayout(indicator5Layout);
        indicator5Layout.setHorizontalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator5Layout.setVerticalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hover4Layout = new javax.swing.GroupLayout(hover4);
        hover4.setLayout(hover4Layout);
        hover4Layout.setHorizontalGroup(
            hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover4Layout.createSequentialGroup()
                .addComponent(indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(report)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hover4Layout.setVerticalGroup(
            hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(report)
                .addContainerGap())
            .addComponent(indicator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hover5.setBackground(new java.awt.Color(255, 255, 255));
        hover5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover5MouseExited(evt);
            }
        });

        about.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        about.setText("About Us");

        indicator6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator6Layout = new javax.swing.GroupLayout(indicator6);
        indicator6.setLayout(indicator6Layout);
        indicator6Layout.setHorizontalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator6Layout.setVerticalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hover5Layout = new javax.swing.GroupLayout(hover5);
        hover5.setLayout(hover5Layout);
        hover5Layout.setHorizontalGroup(
            hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover5Layout.createSequentialGroup()
                .addComponent(indicator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(about)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hover5Layout.setVerticalGroup(
            hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about)
                .addContainerGap())
            .addComponent(indicator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hover2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hover3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hover4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hover5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(hover1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hover2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hover3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hover4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hover5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/deb.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(247, 240, 241));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Debopriya Deb Roy");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Dhaka,Bangladesh");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("CSE,AUST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1)))
                .addContainerGap(1841, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1166, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hover5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover5MouseExited
        // TODO add your handling code here:
        indicator6.setBackground(new Color(255, 255, 255));
        hover5.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_hover5MouseExited

    private void hover5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover5MouseEntered
        // TODO add your handling code here:
        indicator6.setBackground(new Color(0, 0, 0));
        hover5.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_hover5MouseEntered

    private void hover4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover4MouseExited
        // TODO add your handling code here:
        indicator5.setBackground(new Color(255, 255, 255));
        hover4.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_hover4MouseExited

    private void hover4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover4MouseEntered
        // TODO add your handling code here:
        indicator5.setBackground(new Color(0, 0, 0));
        hover4.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_hover4MouseEntered

    private void hover3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseExited
        // TODO add your handling code here:
        indicator4.setBackground(new Color(255, 255, 255));
        hover3.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_hover3MouseExited

    private void hover3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseEntered
        // TODO add your handling code here:
        indicator4.setBackground(new Color(0, 0, 0));
        hover3.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_hover3MouseEntered

    private void hover2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover2MouseExited
        // TODO add your handling code here:
        indicator3.setBackground(new Color(255, 255, 255));
        hover2.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_hover2MouseExited

    private void hover2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover2MouseEntered
        // TODO add your handling code here:
        indicator3.setBackground(new Color(0, 0, 0));
        hover2.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_hover2MouseEntered

    private void hover4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover4MouseClicked
            Report r1 = new Report();
            r1.setVisible(true);
    }//GEN-LAST:event_hover4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel dash;
    private javax.swing.JLabel fina;
    private javax.swing.JLabel home;
    private javax.swing.JPanel hover1;
    private javax.swing.JPanel hover2;
    private javax.swing.JPanel hover3;
    private javax.swing.JPanel hover4;
    private javax.swing.JPanel hover5;
    private javax.swing.JPanel indicator2;
    private javax.swing.JPanel indicator3;
    private javax.swing.JPanel indicator4;
    private javax.swing.JPanel indicator5;
    private javax.swing.JPanel indicator6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel report;
    // End of variables declaration//GEN-END:variables
}
