/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hello iT
 */
public class Dashboard extends javax.swing.JFrame implements frame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    int id = Integer.parseInt(signIN.id);

    public Dashboard() {
        initComponents();
        conn = databaseConnection.connectdb();
        String query = "SELECT FirstName,LastName,UserName,University,MobileNo,LocalG,LocalGNum,EmailAdd,BloodG\n"
                + "FROM  userinfo\n"
                + "WHERE UserID='" + id + "'";
        String query1 = "SELECT Picture\n"
                + "FROM userinfo\n"
                + "WHERE UserID='" + id + "'";
        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

//            ResultSet rs1 = st.executeQuery(query1);
//            while (rs1.next()) {
//                BufferedImage im;
//                try {
//                    im = ImageIO.read(rs.getBinaryStream("Picture"));
//                    display_Photo.setIcon(new ImageIcon(im));
//                } catch (IOException ex) {
//                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
//                }
//
//            }
            rs.next();
            user1.setText(rs.getString("UserName"));
            uni1.setText(rs.getString("University"));
            mobile1.setText(rs.getString("MobileNo"));
            email1.setText(rs.getString("EmailAdd"));
            bld1.setText(rs.getString("BloodG"));
            local1.setText(rs.getString("LocalG"));
            L_Num1.setText(rs.getString("LocalGNum"));
            F_name.setText(rs.getString("FirstName"));
            L_Name.setText(rs.getString("LastName"));

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

//        try {
//            rs = st.executeQuery(query1);
//            while (rs.next()) {
//                BufferedImage im;
//                try {
//                    im = ImageIO.read(rs.getBinaryStream("Picture"));
//                    display_Photo.setIcon(new ImageIcon(im));
//                } catch (IOException ex) {
//                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
//                }
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboardBox = new javax.swing.JPanel();
        dash = new javax.swing.JLabel();
        indicator2 = new javax.swing.JPanel();
        financesBox = new javax.swing.JPanel();
        fina = new javax.swing.JLabel();
        indicator3 = new javax.swing.JPanel();
        homemateBox = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        indicator4 = new javax.swing.JPanel();
        About = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        indicator5 = new javax.swing.JPanel();
        Log_Out = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        indicator6 = new javax.swing.JPanel();
        display_Photo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uni = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        bld = new javax.swing.JLabel();
        local = new javax.swing.JLabel();
        L_Num = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        uni1 = new javax.swing.JLabel();
        mobile1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        bld1 = new javax.swing.JLabel();
        local1 = new javax.swing.JLabel();
        L_Num1 = new javax.swing.JLabel();
        L_Num2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        L_Name = new javax.swing.JLabel();
        F_name = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dashboardBox.setBackground(new java.awt.Color(1, 122, 255));

        dash.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dash.setForeground(new java.awt.Color(240, 240, 240));
        dash.setText("Dashboard");

        indicator2.setBackground(new java.awt.Color(0, 97, 204));

        javax.swing.GroupLayout indicator2Layout = new javax.swing.GroupLayout(indicator2);
        indicator2.setLayout(indicator2Layout);
        indicator2Layout.setHorizontalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator2Layout.setVerticalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardBoxLayout = new javax.swing.GroupLayout(dashboardBox);
        dashboardBox.setLayout(dashboardBoxLayout);
        dashboardBoxLayout.setHorizontalGroup(
            dashboardBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardBoxLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(dash)
                .addGap(0, 129, Short.MAX_VALUE))
            .addGroup(dashboardBoxLayout.createSequentialGroup()
                .addComponent(indicator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        dashboardBoxLayout.setVerticalGroup(
            dashboardBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dash)
                .addContainerGap())
            .addComponent(indicator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        financesBox.setBackground(new java.awt.Color(255, 255, 255));
        financesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financesBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                financesBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                financesBoxMouseExited(evt);
            }
        });

        fina.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fina.setText("Finances");

        indicator3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout financesBoxLayout = new javax.swing.GroupLayout(financesBox);
        financesBox.setLayout(financesBoxLayout);
        financesBoxLayout.setHorizontalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financesBoxLayout.createSequentialGroup()
                .addComponent(indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fina)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        financesBoxLayout.setVerticalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financesBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fina)
                .addContainerGap())
            .addComponent(indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        homemateBox.setBackground(new java.awt.Color(255, 255, 255));
        homemateBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homemateBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homemateBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homemateBoxMouseExited(evt);
            }
        });

        home.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        home.setText("Homemate");

        indicator4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator4Layout = new javax.swing.GroupLayout(indicator4);
        indicator4.setLayout(indicator4Layout);
        indicator4Layout.setHorizontalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator4Layout.setVerticalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout homemateBoxLayout = new javax.swing.GroupLayout(homemateBox);
        homemateBox.setLayout(homemateBoxLayout);
        homemateBoxLayout.setHorizontalGroup(
            homemateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homemateBoxLayout.createSequentialGroup()
                .addComponent(indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(home)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homemateBoxLayout.setVerticalGroup(
            homemateBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homemateBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home)
                .addContainerGap())
            .addComponent(indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });

        report.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        report.setText("About Us");

        indicator5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator5Layout = new javax.swing.GroupLayout(indicator5);
        indicator5.setLayout(indicator5Layout);
        indicator5Layout.setHorizontalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator5Layout.setVerticalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addComponent(indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(report)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(report)
                .addContainerGap())
            .addComponent(indicator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Log_Out.setBackground(new java.awt.Color(255, 255, 255));
        Log_Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_OutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Log_OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Log_OutMouseExited(evt);
            }
        });

        about.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        about.setText("Log Out");

        indicator6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator6Layout = new javax.swing.GroupLayout(indicator6);
        indicator6.setLayout(indicator6Layout);
        indicator6Layout.setHorizontalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator6Layout.setVerticalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Log_OutLayout = new javax.swing.GroupLayout(Log_Out);
        Log_Out.setLayout(Log_OutLayout);
        Log_OutLayout.setHorizontalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_OutLayout.createSequentialGroup()
                .addComponent(indicator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(about)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Log_OutLayout.setVerticalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Log_OutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about)
                .addContainerGap())
            .addComponent(indicator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(financesBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homemateBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Log_Out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(dashboardBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(financesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homemateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        display_Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/deb.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 122, 255));

        uni.setBackground(new java.awt.Color(1, 122, 255));
        uni.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        uni.setForeground(new java.awt.Color(1, 122, 255));
        uni.setText("University ");

        mobile.setBackground(new java.awt.Color(1, 122, 255));
        mobile.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        mobile.setForeground(new java.awt.Color(1, 122, 255));
        mobile.setText("Mobile No ");

        email.setBackground(new java.awt.Color(1, 122, 255));
        email.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        email.setForeground(new java.awt.Color(1, 122, 255));
        email.setText("Email Account ");

        bld.setBackground(new java.awt.Color(1, 122, 255));
        bld.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        bld.setForeground(new java.awt.Color(1, 122, 255));
        bld.setText("Blood Group ");

        local.setBackground(new java.awt.Color(1, 122, 255));
        local.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        local.setForeground(new java.awt.Color(1, 122, 255));
        local.setText("Local Guardian ");

        L_Num.setBackground(new java.awt.Color(1, 122, 255));
        L_Num.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        L_Num.setForeground(new java.awt.Color(1, 122, 255));
        L_Num.setText("Guardian Number ");

        user1.setBackground(new java.awt.Color(1, 122, 255));
        user1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        user1.setForeground(new java.awt.Color(51, 51, 51));
        user1.setText("Guardian Number >>");

        uni1.setBackground(new java.awt.Color(1, 122, 255));
        uni1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        uni1.setForeground(new java.awt.Color(51, 51, 51));
        uni1.setText("Guardian Number >>");

        mobile1.setBackground(new java.awt.Color(1, 122, 255));
        mobile1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mobile1.setForeground(new java.awt.Color(51, 51, 51));
        mobile1.setText("Guardian Number >>");

        email1.setBackground(new java.awt.Color(1, 122, 255));
        email1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(51, 51, 51));
        email1.setText("Guardian Number >>");

        bld1.setBackground(new java.awt.Color(1, 122, 255));
        bld1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        bld1.setForeground(new java.awt.Color(51, 51, 51));
        bld1.setText("Guardian Number >>");

        local1.setBackground(new java.awt.Color(1, 122, 255));
        local1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        local1.setForeground(new java.awt.Color(51, 51, 51));
        local1.setText("Guardian Number >>");

        L_Num1.setBackground(new java.awt.Color(1, 122, 255));
        L_Num1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        L_Num1.setForeground(new java.awt.Color(51, 51, 51));
        L_Num1.setText("Guardian Number >>");

        L_Num2.setBackground(new java.awt.Color(1, 122, 255));
        L_Num2.setFont(new java.awt.Font("Calibri", 1, 29)); // NOI18N
        L_Num2.setForeground(new java.awt.Color(102, 102, 102));
        L_Num2.setText("Profile");

        user.setBackground(new java.awt.Color(1, 122, 255));
        user.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        user.setForeground(new java.awt.Color(1, 122, 255));
        user.setText("User Name ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(L_Num2)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uni)
                            .addComponent(mobile)
                            .addComponent(email)
                            .addComponent(bld)
                            .addComponent(local)
                            .addComponent(L_Num)
                            .addComponent(user))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uni1)
                            .addComponent(user1)
                            .addComponent(mobile1)
                            .addComponent(email1)
                            .addComponent(bld1)
                            .addComponent(local1)
                            .addComponent(L_Num1))
                        .addGap(145, 145, 145))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jLabel4)
                    .addContainerGap(659, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(L_Num2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user1)
                    .addComponent(user))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uni1)
                    .addComponent(uni))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile1)
                    .addComponent(mobile))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bld)
                    .addComponent(bld1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(local)
                    .addComponent(local1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Num)
                    .addComponent(L_Num1))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jLabel4)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        Welcome.setBackground(new java.awt.Color(1, 122, 255));
        Welcome.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(51, 51, 51));
        Welcome.setText("Welcome Back ,");

        L_Name.setBackground(new java.awt.Color(1, 122, 255));
        L_Name.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        L_Name.setForeground(new java.awt.Color(51, 51, 51));
        L_Name.setText("Last");

        F_name.setBackground(new java.awt.Color(1, 122, 255));
        F_name.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        F_name.setForeground(new java.awt.Color(51, 51, 51));
        F_name.setText("Name");

        user4.setBackground(new java.awt.Color(1, 122, 255));
        user4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        user4.setForeground(new java.awt.Color(1, 122, 255));
        user4.setText("Nice To Meat You");

        user5.setBackground(new java.awt.Color(1, 122, 255));
        user5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        user5.setForeground(new java.awt.Color(1, 122, 255));
        user5.setText("HAVE A NICE DAY!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(display_Photo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(user4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(user5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Welcome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L_Name)))))
                .addContainerGap(1582, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Welcome)
                    .addComponent(F_name)
                    .addComponent(L_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user4)
                    .addComponent(user5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(display_Photo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1137, 712));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Log_OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseExited
        // TODO add your handling code here:
        indicator6.setBackground(new Color(255, 255, 255));
        Log_Out.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Log_OutMouseExited

    private void Log_OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseEntered
        // TODO add your handling code here:
        indicator6.setBackground(new Color(0, 0, 0));
        Log_Out.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_Log_OutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        // TODO add your handling code here:
        indicator5.setBackground(new Color(255, 255, 255));
        About.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_AboutMouseExited

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        // TODO add your handling code here:
        indicator5.setBackground(new Color(0, 0, 0));
        About.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_AboutMouseEntered

    private void homemateBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homemateBoxMouseExited
        // TODO add your handling code here:
        indicator4.setBackground(new Color(255, 255, 255));
        homemateBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_homemateBoxMouseExited

    private void homemateBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homemateBoxMouseEntered
        // TODO add your handling code here:
        indicator4.setBackground(new Color(0, 0, 0));
        homemateBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_homemateBoxMouseEntered

    private void financesBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseExited
        // TODO add your handling code here:
        indicator3.setBackground(new Color(255, 255, 255));
        financesBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_financesBoxMouseExited

    private void financesBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseEntered
        // TODO add your handling code here:
        indicator3.setBackground(new Color(0, 0, 0));
        financesBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_financesBoxMouseEntered

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        About a = new About();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AboutMouseClicked

    private void Log_OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Log Out From Your Account!", "Hey", 1);
        signIN.id = null;
        signIN s = new signIN();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Log_OutMouseClicked

    private void financesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseClicked
        // TODO add your handling code here:
        M_Finance f = new M_Finance();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financesBoxMouseClicked

    private void homemateBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homemateBoxMouseClicked
        // TODO add your handling code here:
        homemate h = new homemate();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homemateBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JLabel F_name;
    private javax.swing.JLabel L_Name;
    private javax.swing.JLabel L_Num;
    private javax.swing.JLabel L_Num1;
    private javax.swing.JLabel L_Num2;
    private javax.swing.JPanel Log_Out;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel about;
    private javax.swing.JLabel bld;
    private javax.swing.JLabel bld1;
    private javax.swing.JLabel dash;
    private javax.swing.JPanel dashboardBox;
    private javax.swing.JLabel display_Photo;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel fina;
    private javax.swing.JPanel financesBox;
    private javax.swing.JLabel home;
    private javax.swing.JPanel homemateBox;
    private javax.swing.JPanel indicator2;
    private javax.swing.JPanel indicator3;
    private javax.swing.JPanel indicator4;
    private javax.swing.JPanel indicator5;
    private javax.swing.JPanel indicator6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel local;
    private javax.swing.JLabel local1;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel mobile1;
    private javax.swing.JLabel report;
    private javax.swing.JLabel uni;
    private javax.swing.JLabel uni1;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    // End of variables declaration//GEN-END:variables
}
