/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hello iT
 */
public class Dashboard_admin extends javax.swing.JFrame implements frame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    static int a[] = new int[8];

    /**
     * Creates new form about
     */
    public Dashboard_admin() {
        initComponents();
        conn = databaseConnection.connectdb();

        String query = "SELECT  UserID ,CONCAT(FirstName, ' ', LastName) as fullname FROM userinfo where UserID !=6";
        String query1 = "SELECT SUM(Send_money),SUM(MealQuan), SUM(additional.A_Cost),COUNT(UserID) FROM userinfo,additional WHERE id!=6";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            user1.setText(rs.getString("fullname"));
            a[0] = rs.getInt("UserID");
            System.out.println(a[0]);
            rs.next();
            user2.setText(rs.getString("fullname"));
            a[1] = rs.getInt("UserID");
            System.out.println(a[1]);
            rs.next();
            user3.setText(rs.getString("fullname"));
            a[2] = rs.getInt("UserID");
            System.out.println(a[2]);
            rs.next();
            user4.setText(rs.getString("fullname"));
            a[3] = rs.getInt("UserID");
            System.out.println(a[3]);
            rs.next();
            user5.setText(rs.getString("fullname"));
            a[4] = rs.getInt("UserID");
            System.out.println(a[4]);
            rs.next();
            user6.setText(rs.getString("fullname"));
            a[5] = rs.getInt("UserID");
            System.out.println(a[5]);
            rs.next();
            user7.setText(rs.getString("fullname"));
            a[6] = rs.getInt("UserID");
            System.out.println(a[6]);
            rs.next();
            user8.setText(rs.getString("fullname"));
            a[7] = rs.getInt("UserID");
            System.out.println(a[7]);

        } catch (Exception ex) {
            System.out.println(ex);
        }
        try {
            rs = st.executeQuery(query1);
            rs.next();
            Double S_money = rs.getDouble(1);
            Double M_Quan = rs.getDouble(2);
            Double A_Cost = rs.getDouble(3);
            int M_c = rs.getInt(4)-1;

            T_Amount.setText(Double.toString(S_money));
            T_Meal.setText(Double.toString((M_Quan)));
            T_Add.setText(Double.toString(A_Cost));
            T_member.setText(Integer.toString(M_c));

        } catch (Exception e) {
            System.out.println("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        indicator5 = new javax.swing.JPanel();
        financesBox = new javax.swing.JPanel();
        fina = new javax.swing.JLabel();
        indicator3 = new javax.swing.JPanel();
        Home_Mate = new javax.swing.JPanel();
        indicator6 = new javax.swing.JPanel();
        Log_Out = new javax.swing.JPanel();
        j = new javax.swing.JLabel();
        indicator4 = new javax.swing.JPanel();
        About = new javax.swing.JPanel();
        Log_Out1 = new javax.swing.JLabel();
        indicator7 = new javax.swing.JPanel();
        Home_Mate1 = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        indicator8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        user7 = new javax.swing.JLabel();
        user8 = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();
        user6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MQuan = new javax.swing.JLabel();
        GivenCost = new javax.swing.JLabel();
        TMealCost = new javax.swing.JLabel();
        TNetCost = new javax.swing.JLabel();
        MealQuanValue = new javax.swing.JLabel();
        Send_moneyValue = new javax.swing.JLabel();
        MealCostValue = new javax.swing.JLabel();
        Net_amountValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        T_Amount = new javax.swing.JLabel();
        T_Meal = new javax.swing.JLabel();
        T_Add = new javax.swing.JLabel();
        T_member = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        indicator5.setBackground(new java.awt.Color(255, 255, 255));

        financesBox.setBackground(new java.awt.Color(255, 255, 255));
        financesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financesBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                financesBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                financesBoxMouseExited(evt);
            }
        });

        fina.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fina.setText("Finances");

        indicator3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout financesBoxLayout = new javax.swing.GroupLayout(financesBox);
        financesBox.setLayout(financesBoxLayout);
        financesBoxLayout.setHorizontalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financesBoxLayout.createSequentialGroup()
                .addComponent(indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fina)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        financesBoxLayout.setVerticalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financesBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fina)
                .addContainerGap())
            .addComponent(indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Home_Mate.setBackground(new java.awt.Color(1, 122, 255));
        Home_Mate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_MateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home_MateMouseExited(evt);
            }
        });

        indicator6.setBackground(new java.awt.Color(0, 97, 204));

        javax.swing.GroupLayout indicator6Layout = new javax.swing.GroupLayout(indicator6);
        indicator6.setLayout(indicator6Layout);
        indicator6Layout.setHorizontalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator6Layout.setVerticalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Home_MateLayout = new javax.swing.GroupLayout(Home_Mate);
        Home_Mate.setLayout(Home_MateLayout);
        Home_MateLayout.setHorizontalGroup(
            Home_MateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_MateLayout.createSequentialGroup()
                .addComponent(indicator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );
        Home_MateLayout.setVerticalGroup(
            Home_MateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Log_Out.setBackground(new java.awt.Color(255, 255, 255));
        Log_Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_OutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Log_OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Log_OutMouseExited(evt);
            }
        });

        j.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        j.setText("Log Out");

        indicator4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator4Layout = new javax.swing.GroupLayout(indicator4);
        indicator4.setLayout(indicator4Layout);
        indicator4Layout.setHorizontalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator4Layout.setVerticalGroup(
            indicator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Log_OutLayout = new javax.swing.GroupLayout(Log_Out);
        Log_Out.setLayout(Log_OutLayout);
        Log_OutLayout.setHorizontalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_OutLayout.createSequentialGroup()
                .addComponent(indicator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(j)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Log_OutLayout.setVerticalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Log_OutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j)
                .addContainerGap())
            .addComponent(indicator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });

        Log_Out1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Log_Out1.setText("About");

        indicator7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator7Layout = new javax.swing.GroupLayout(indicator7);
        indicator7.setLayout(indicator7Layout);
        indicator7Layout.setHorizontalGroup(
            indicator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator7Layout.setVerticalGroup(
            indicator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLayout.createSequentialGroup()
                .addComponent(indicator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Log_Out1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Log_Out1)
                .addContainerGap())
            .addComponent(indicator7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Home_Mate1.setBackground(new java.awt.Color(1, 122, 255));
        Home_Mate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_Mate1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home_Mate1MouseExited(evt);
            }
        });

        about.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("DashBoard");

        indicator8.setBackground(new java.awt.Color(0, 97, 204));

        javax.swing.GroupLayout indicator8Layout = new javax.swing.GroupLayout(indicator8);
        indicator8.setLayout(indicator8Layout);
        indicator8Layout.setHorizontalGroup(
            indicator8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator8Layout.setVerticalGroup(
            indicator8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Home_Mate1Layout = new javax.swing.GroupLayout(Home_Mate1);
        Home_Mate1.setLayout(Home_Mate1Layout);
        Home_Mate1Layout.setHorizontalGroup(
            Home_Mate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_Mate1Layout.createSequentialGroup()
                .addComponent(indicator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(about)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Home_Mate1Layout.setVerticalGroup(
            Home_Mate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_Mate1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(about)
                .addContainerGap())
            .addComponent(indicator8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout indicator5Layout = new javax.swing.GroupLayout(indicator5);
        indicator5.setLayout(indicator5Layout);
        indicator5Layout.setHorizontalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financesBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(indicator5Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(Home_Mate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Log_Out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Home_Mate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        indicator5Layout.setVerticalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indicator5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(financesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Home_Mate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Home_Mate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        user7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user7.setText("No Member");
        user7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user7MouseExited(evt);
            }
        });

        user8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user8.setText("No Member");
        user8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user8MouseExited(evt);
            }
        });

        user4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user4.setText("No Member");
        user4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user4MouseExited(evt);
            }
        });

        user5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user5.setText("No Member");
        user5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user5MouseExited(evt);
            }
        });

        user1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user1.setText("No Member");
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user1MouseExited(evt);
            }
        });

        user2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user2.setText("No Member");
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user2MouseExited(evt);
            }
        });

        user3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user3.setText("No Member");
        user3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user3MouseExited(evt);
            }
        });

        user6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        user6.setText("No Member");
        user6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(user2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(user1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(user4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(user6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(user5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user1)
                    .addComponent(user4)
                    .addComponent(user7))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user2)
                    .addComponent(user5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user3)
                            .addComponent(user6))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 122, 255));
        jLabel2.setText("Admin DashBoard");

        MQuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MQuan.setText("Meal Quantity");

        GivenCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GivenCost.setText("Given Cost");

        TMealCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TMealCost.setText("Total Meal Cost");

        TNetCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TNetCost.setText("Total Net Cost");

        MealQuanValue.setText("00.00");

        Send_moneyValue.setText("00.00");

        MealCostValue.setText("00.00");

        Net_amountValue.setBackground(new java.awt.Color(0, 153, 255));
        Net_amountValue.setText("00.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MQuan)
                    .addComponent(TNetCost)
                    .addComponent(TMealCost)
                    .addComponent(GivenCost))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MealCostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(MealQuanValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Send_moneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Net_amountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MQuan)
                    .addComponent(MealQuanValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GivenCost)
                    .addComponent(Send_moneyValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TMealCost)
                    .addComponent(MealCostValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TNetCost)
                    .addComponent(Net_amountValue))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Total Meal Amount ");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setText("Total Meal");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setText("Total Additional Cost:");

        T_Amount.setText("0.00");

        T_Meal.setText("jLabel1");

        T_Add.setText("jLabel1");

        T_member.setText("jLabel1");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setText("Total Member");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T_member)
                    .addComponent(T_Add)
                    .addComponent(T_Meal)
                    .addComponent(T_Amount))
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T_Amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(T_Meal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(T_Add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(T_member))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel2)))
                .addContainerGap(2297, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1136, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home_MateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_MateMouseExited
        // TODO add your handling code here:
//        indicator6.setBackground(new Color(255, 255, 255));
//        aboutBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Home_MateMouseExited

    private void Home_MateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_MateMouseEntered
        // TODO add your handling code here:
//        indicator6.setBackground(new Color(0, 0, 0));
//        aboutBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_Home_MateMouseEntered

    private void Log_OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseExited
        // TODO add your handling code here:
        indicator4.setBackground(new Color(255, 255, 255));
        Log_Out.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Log_OutMouseExited

    private void Log_OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseEntered
        // TODO add your handling code here:
//          indicator5.setBackground(new Color(0, 0, 0));
//        Log_Out.setBackground(new Color(247,59,63));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_Log_OutMouseEntered

    private void financesBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseExited
        // TODO add your handling code here:
        indicator3.setBackground(new Color(255, 255, 255));
        financesBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_financesBoxMouseExited

    private void financesBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseEntered
        // TODO add your handling code here:
        indicator3.setBackground(new Color(0, 0, 0));
        financesBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_financesBoxMouseEntered

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        // TODO add your handling code here:
        indicator7.setBackground(new Color(0, 0, 0));
        About.setBackground(new Color(232, 232, 232));
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        // TODO add your handling code here:
        indicator7.setBackground(new Color(255, 255, 255));
        About.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_AboutMouseExited

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        // TODO add your handling code here:
        About1 a = new About1();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AboutMouseClicked

    private void Log_OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Log Out From Your Account!", "Hey", 1);
        signIN.id = null;
        signIN s = new signIN();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Log_OutMouseClicked

    private void financesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseClicked
        // TODO add your handling code here:
        NewJFrame1 f = new NewJFrame1();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financesBoxMouseClicked

    private void user1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseEntered
        user1.setForeground(new Color(1, 122, 255));
        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 1";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_user1MouseEntered

    private void user1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseExited
        user1.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user1MouseExited

    private void user2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseEntered
        user2.setForeground(new Color(1, 122, 255));

        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 2";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_user2MouseEntered

    private void user2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseExited
        user2.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user2MouseExited

    private void user3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseEntered
        user3.setForeground(new Color(1, 122, 255));
        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 3";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_user3MouseEntered

    private void user3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseExited
        user3.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_user3MouseExited

    private void user4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4MouseEntered
        user4.setForeground(new Color(1, 122, 255));

        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 4";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_user4MouseEntered

    private void user4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4MouseExited
        user4.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user4MouseExited

    private void user5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5MouseEntered
        user5.setForeground(new Color(1, 122, 255));

        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 5";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_user5MouseEntered

    private void user5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5MouseExited
        user5.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user5MouseExited

    private void user6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6MouseEntered
        user6.setForeground(new Color(1, 122, 255));

        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 6";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_user6MouseEntered

    private void user6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6MouseExited
        user6.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user6MouseExited

    private void user7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user7MouseEntered
        user7.setForeground(new Color(1, 122, 255));

        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 7";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_user7MouseEntered

    private void user7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user7MouseExited
        user7.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user7MouseExited

    private void user8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user8MouseEntered
        user8.setForeground(new Color(1, 122, 255));

        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 8";

        try {
            st = conn.createStatement();
            rs = st.executeQuery(query);

            rs.next();
            MealQuanValue.setText(rs.getString("MealQuan"));
            Send_moneyValue.setText(rs.getString("Send_money"));
            MealCostValue.setText(rs.getString("MealCost"));
            Net_amountValue.setText(rs.getString("Net_amount"));

        } catch (Exception ex) {
            System.out.println(ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_user8MouseEntered

    private void user8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user8MouseExited
        user8.setForeground(new Color(0, 0, 0));
        MealQuanValue.setText("0");
        Send_moneyValue.setText("0");
        MealCostValue.setText("0");
        Net_amountValue.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_user8MouseExited

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked
        String query = "SELECT Send_money, Net_amount, MealQuan, MealCost FROM userinfo WHERE UserID = 1";

        try {
                Member_Print m=  new Member_Print(a[0]);
                m.setVisible(true);

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_user1MouseClicked

    private void Home_Mate1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_Mate1MouseEntered
        // TODO add your handling code here:
        //        indicator6.setBackground(new Color(0, 0, 0));
        //        aboutBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_Home_Mate1MouseEntered

    private void Home_Mate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_Mate1MouseExited
        // TODO add your handling code here:
        //        indicator6.setBackground(new Color(255, 255, 255));
        //        aboutBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Home_Mate1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JLabel GivenCost;
    private javax.swing.JPanel Home_Mate;
    private javax.swing.JPanel Home_Mate1;
    private javax.swing.JPanel Log_Out;
    private javax.swing.JLabel Log_Out1;
    private javax.swing.JLabel MQuan;
    private javax.swing.JLabel MealCostValue;
    private javax.swing.JLabel MealQuanValue;
    private javax.swing.JLabel Net_amountValue;
    private javax.swing.JLabel Send_moneyValue;
    private javax.swing.JLabel TMealCost;
    private javax.swing.JLabel TNetCost;
    private javax.swing.JLabel T_Add;
    private javax.swing.JLabel T_Amount;
    private javax.swing.JLabel T_Meal;
    private javax.swing.JLabel T_member;
    private javax.swing.JLabel about;
    private javax.swing.JLabel fina;
    private javax.swing.JPanel financesBox;
    private javax.swing.JPanel indicator3;
    private javax.swing.JPanel indicator4;
    private javax.swing.JPanel indicator5;
    private javax.swing.JPanel indicator6;
    private javax.swing.JPanel indicator7;
    private javax.swing.JPanel indicator8;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    private javax.swing.JLabel user6;
    private javax.swing.JLabel user7;
    private javax.swing.JLabel user8;
    // End of variables declaration//GEN-END:variables
}
