/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static management.frame.ab1;
import static management.frame.r1;

/**
 *
 * @author ddroy
 */
public class NewJFrame1 extends javax.swing.JFrame implements frame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    static String Date;

    /**
     * Creates new form signIN
     */
    public NewJFrame1() {
        initComponents();
        conn = databaseConnection.connectdb();
        DateFormat df = new SimpleDateFormat("dd/MM/yy");
        Calendar calobj = Calendar.getInstance();
        date.setText(df.format(calobj.getTime()));
        Date = df.format(calobj.getTime());
        updateComboboxMeal();

        /**
         * Creates new form NewJFrame1
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dashboardBox = new javax.swing.JPanel();
        dash = new javax.swing.JLabel();
        indicator2 = new javax.swing.JPanel();
        financesBox = new javax.swing.JPanel();
        fina = new javax.swing.JLabel();
        indicator3 = new javax.swing.JPanel();
        about1 = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        indicator5 = new javax.swing.JPanel();
        Log_Out = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        indicator6 = new javax.swing.JPanel();
        jpanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AddCost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ShopItemName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MemberName_shop = new javax.swing.JComboBox<>();
        Amount = new javax.swing.JTextField();
        AddItem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        MealQ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Name_Meal = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        ShopSubmit = new javax.swing.JLabel();
        MealSubmit = new javax.swing.JLabel();
        calculate = new javax.swing.JLabel();
        clearShop = new javax.swing.JLabel();
        clearMeal = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dashboardBox.setBackground(java.awt.Color.white);
        dashboardBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardBoxMouseExited(evt);
            }
        });

        dash.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        dash.setText("Dashboard");

        indicator2.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout indicator2Layout = new javax.swing.GroupLayout(indicator2);
        indicator2.setLayout(indicator2Layout);
        indicator2Layout.setHorizontalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator2Layout.setVerticalGroup(
            indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardBoxLayout = new javax.swing.GroupLayout(dashboardBox);
        dashboardBox.setLayout(dashboardBoxLayout);
        dashboardBoxLayout.setHorizontalGroup(
            dashboardBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardBoxLayout.createSequentialGroup()
                .addComponent(indicator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(dash)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        dashboardBoxLayout.setVerticalGroup(
            dashboardBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dash)
                .addContainerGap())
            .addComponent(indicator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        financesBox.setBackground(new java.awt.Color(1, 122, 255));
        financesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                financesBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                financesBoxMouseExited(evt);
            }
        });

        fina.setBackground(java.awt.Color.white);
        fina.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fina.setForeground(java.awt.Color.white);
        fina.setText("Finances");

        indicator3.setBackground(new java.awt.Color(0, 97, 204));

        javax.swing.GroupLayout indicator3Layout = new javax.swing.GroupLayout(indicator3);
        indicator3.setLayout(indicator3Layout);
        indicator3Layout.setHorizontalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator3Layout.setVerticalGroup(
            indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout financesBoxLayout = new javax.swing.GroupLayout(financesBox);
        financesBox.setLayout(financesBoxLayout);
        financesBoxLayout.setHorizontalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financesBoxLayout.createSequentialGroup()
                .addComponent(indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(fina)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        financesBoxLayout.setVerticalGroup(
            financesBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financesBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fina)
                .addContainerGap())
            .addComponent(indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        about1.setBackground(new java.awt.Color(255, 255, 255));
        about1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                about1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about1MouseExited(evt);
            }
        });

        report.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        report.setText("About");

        indicator5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator5Layout = new javax.swing.GroupLayout(indicator5);
        indicator5.setLayout(indicator5Layout);
        indicator5Layout.setHorizontalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator5Layout.setVerticalGroup(
            indicator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout about1Layout = new javax.swing.GroupLayout(about1);
        about1.setLayout(about1Layout);
        about1Layout.setHorizontalGroup(
            about1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(about1Layout.createSequentialGroup()
                .addComponent(indicator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(report)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        about1Layout.setVerticalGroup(
            about1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(about1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(report)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Log_Out.setBackground(new java.awt.Color(255, 255, 255));
        Log_Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_OutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Log_OutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Log_OutMouseExited(evt);
            }
        });

        about.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        about.setText("Log Out");

        indicator6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout indicator6Layout = new javax.swing.GroupLayout(indicator6);
        indicator6.setLayout(indicator6Layout);
        indicator6Layout.setHorizontalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indicator6Layout.setVerticalGroup(
            indicator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Log_OutLayout = new javax.swing.GroupLayout(Log_Out);
        Log_Out.setLayout(Log_OutLayout);
        Log_OutLayout.setHorizontalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Log_OutLayout.createSequentialGroup()
                .addComponent(indicator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(about)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Log_OutLayout.setVerticalGroup(
            Log_OutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indicator6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Log_OutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(about)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(about1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Log_Out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(financesBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(financesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel5.setText("Date");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel9.setText("Additional Item");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel11.setText("Amount");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel13.setText("Additional Cost");

        AddCost.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        AddCost.setText("0");
        AddCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCostActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel1.setText("Item Name: ");

        ShopItemName.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ShopItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopItemNameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel12.setText("Member Name");

        MemberName_shop.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        MemberName_shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberName_shopActionPerformed(evt);
            }
        });

        Amount.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });

        AddItem.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        AddItem.setText(" Nothing");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel14.setText("Meal Quantity ");

        MealQ.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        MealQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealQActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Item Name", "Additional Item", "Additional Cost", "Total Meal"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(17);
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel15.setText("Member Name");

        Name_Meal.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        Name_Meal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Name_MealMouseClicked(evt);
            }
        });
        Name_Meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_MealActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(1, 122, 255));
        jLabel16.setText("Shopping Section");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 122, 255));
        jLabel17.setText("Meal Section");

        date.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        ShopSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/submit_default.png"))); // NOI18N
        ShopSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShopSubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShopSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShopSubmitMouseExited(evt);
            }
        });

        MealSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/submit_default.png"))); // NOI18N
        MealSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MealSubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MealSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MealSubmitMouseExited(evt);
            }
        });

        calculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/calculate (2).png"))); // NOI18N
        calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calculateMouseExited(evt);
            }
        });

        clearShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/clear (1).png"))); // NOI18N
        clearShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearShopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearShopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearShopMouseExited(evt);
            }
        });

        clearMeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/management/clear (1).png"))); // NOI18N
        clearMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMealMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMealMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpanel3Layout = new javax.swing.GroupLayout(jpanel3);
        jpanel3.setLayout(jpanel3Layout);
        jpanel3Layout.setHorizontalGroup(
            jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel3Layout.createSequentialGroup()
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearMeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MealSubmit)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel3Layout.createSequentialGroup()
                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel3Layout.createSequentialGroup()
                                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MealQ, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name_Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(calculate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)))
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel3Layout.createSequentialGroup()
                        .addComponent(clearShop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShopSubmit))
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(30, 30, 30)
                        .addComponent(MemberName_shop, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(ShopItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel3Layout.createSequentialGroup()
                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AddCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jpanel3Layout.setVerticalGroup(
            jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(27, 27, 27)
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Name_Meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(MemberName_shop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel3Layout.createSequentialGroup()
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ShopItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)))
                                    .addGroup(jpanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11))))
                            .addGroup(jpanel3Layout.createSequentialGroup()
                                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MealQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearMeal)
                                    .addComponent(MealSubmit)))))
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearShop)
                            .addComponent(ShopSubmit))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(calculate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 122, 255));
        jLabel2.setText("Calculation of the Day");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearMealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMealMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("clear (1).png"));
        clearMeal.setIcon(i);         // TODO add your handling code here:
    }//GEN-LAST:event_clearMealMouseExited

    private void clearMealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMealMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("clear (2).png"));
        clearMeal.setIcon(i); // TODO add your handling code here:
    }//GEN-LAST:event_clearMealMouseEntered

    private void clearMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMealMouseClicked
        JOptionPane.showMessageDialog(null, "Clear Meal Section", "Hey", 1);
        MealQ.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_clearMealMouseClicked

    private void clearShopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearShopMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("clear (1).png"));
        clearShop.setIcon(i);         // TODO add your handling code here:
    }//GEN-LAST:event_clearShopMouseExited

    private void clearShopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearShopMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("clear (2).png"));
        clearShop.setIcon(i);         // TODO add your handling code here:
    }//GEN-LAST:event_clearShopMouseEntered

    private void clearShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearShopMouseClicked
        JOptionPane.showMessageDialog(null, "Clear Shop Section", "Hey!", 1);
        Amount.setText(null);
        ShopItemName.setText(null);
        AddCost.setText(null);
        AddItem.setText(null);
        AddItem.setText("Nothing");
        AddCost.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_clearShopMouseClicked

    private void calculateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("calculate (2).png"));
        calculate.setIcon(i);           // TODO add your handling code here:
    }//GEN-LAST:event_calculateMouseExited

    private void calculateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("calculate (1).png"));
        calculate.setIcon(i);     // TODO add your handling code here:
    }//GEN-LAST:event_calculateMouseEntered

    private void calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseClicked

        String query = "SELECT SUM(MealQuan),SUM(Send_money),COUNT(UserID)\n"
                + "FROM userinfo\n"
                + "WHERE userID>=1";

        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            rs.next();

            double totalMeal = rs.getDouble(1);
            double totalAmount = rs.getDouble(2);
            int totalId = rs.getInt(3);
            double mealPerCost = totalAmount / totalMeal;

            System.out.println("Total Amount: " + totalAmount);
            System.out.println("Total Meal: " + totalMeal);
            System.out.println("Total Id: " + totalId);
            System.out.println("Total Cost per Meal: " + totalAmount / totalMeal);

            query = "SELECT UserID,MealQuan,Send_money\n"
                    + "From userinfo \n"
                    + "WHERE userID>=1";

            st = conn.createStatement();
            rs = st.executeQuery(query);

            double Meal[] = new double[totalId];
            double Id[] = new double[totalId];
            double total[] = new double[totalId];
            double netAmount[] = new double[totalId];
            double amnt[] = new double[totalId];

            for (int i = 0; i < totalId; i++) {
                rs.next();
                Meal[i] = rs.getDouble("MealQuan");
                Id[i] = rs.getDouble("userID");
                amnt[i] = rs.getDouble("Send_money");
                total[i] = Meal[i] * mealPerCost;
                netAmount[i] = amnt[i] - total[i];

            }

            for (int i = 0; i < totalId; i++) {
                String query1 = "UPDATE userinfo\n"
                        + "SET MealCost='" + total[i] + "',\n"
                        + "Net_amount='" + netAmount[i] + "'\n"
                        + "WHERE UserID ='" + Id[i] + "'";
                //                System.out.println(Meal[i]);
                //                System.out.println(Id[i]);
                st.executeUpdate(query1);
                System.out.println(total[i]);
                Amount.setText(null);
                ShopItemName.setText(null);
                AddItem.setText("Nothing");
                AddCost.setText("0");
                MealQ.setText(null);

            }
            JOptionPane.showMessageDialog(null, "Successfully Calculated! ", "Hey", 0);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_calculateMouseClicked

    private void MealSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealSubmitMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("submit_default.png"));
        MealSubmit.setIcon(i);
    }//GEN-LAST:event_MealSubmitMouseExited

    private void MealSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealSubmitMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("submit_hover.png"));
        MealSubmit.setIcon(i);
    }//GEN-LAST:event_MealSubmitMouseEntered

    private void MealSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealSubmitMouseClicked

        if (MealQ.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field remaining", "Warning", 0);
        } else {
            JOptionPane.showMessageDialog(null, "Successfully Save In DataBase", "Hey!", 0);
            String getComboName = Name_Meal.getSelectedItem().toString();
            getComboName = getComboName.substring(0, 2);
            int getID;
            try {
                getID = Integer.parseInt(getComboName);
                System.out.println(getID);
            } catch (Exception e) {
                getComboName = getComboName.substring(0, 1);
                getID = Integer.parseInt(getComboName);
                System.out.println(getID);
            }

            String query = "SELECT MealQuan\n"
                    + "FROM userinfo\n"
                    + "WHERE UserID= '" + getID + "'\n";
            try {
                st = conn.createStatement();
                rs = st.executeQuery(query);
                rs.next();
                String m = rs.getString("MealQuan");
                System.out.println(m);
                int meal = Integer.parseInt(m) + Integer.parseInt(MealQ.getText());
                System.out.println("New Meal " + meal);

                query = "UPDATE userinfo\n"
                        + "SET MealQuan='" + meal + "'\n"
                        + "WHERE UserID ='" + getID + "'";
                st.executeUpdate(query);
                MealQ.setText(null);
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_MealSubmitMouseClicked

    private void ShopSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopSubmitMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("submit_default.png"));
        ShopSubmit.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_ShopSubmitMouseExited

    private void ShopSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopSubmitMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("submit_hover.png"));
        ShopSubmit.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_ShopSubmitMouseEntered

    private void ShopSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopSubmitMouseClicked

        if (date.getText().isEmpty() || Amount.getText().isEmpty() || ShopItemName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field remaining", "Warning", 0);
        } else {

            String getComboName2 = MemberName_shop.getSelectedItem().toString();
            String getComboName1 = getComboName2.substring(2, getComboName2.length());
            getComboName2 = getComboName2.substring(0, 2);
            int getID;
            try {
                getID = Integer.parseInt(getComboName2);
                System.out.println(getID);
            } catch (Exception e) {
                getComboName2 = getComboName2.substring(0, 1);
                getID = Integer.parseInt(getComboName2);
                System.out.println(getID);
            }
            String query = "SELECT Send_money\n"
                    + "FROM userinfo\n"
                    + "WHERE UserID='" + getID + "'";

            System.out.println(Date);
            try {
                st = conn.createStatement();
                rs = st.executeQuery(query);
                rs.next();
                double amnt = rs.getDouble("Send_money");
                System.out.println(amnt);
                amnt = amnt + Double.parseDouble(Amount.getText());
                System.out.println(amnt);
                query = "UPDATE userinfo\n"
                        + "SET Send_money='" + amnt + "'\n"
                        + "WHERE UserID='" + getID + "'";
                st.executeUpdate(query);

                String query1 = "INSERT INTO finance(Date, Name, ItemName, Amount, A_Name) \n"
                        + "VALUES ('" + Date + "','" + getComboName1 + "','" + ShopItemName.getText() + "','" + Amount.getText() + "','" + AddItem.getText() + "')";
                st.executeUpdate(query1);

                query1 = "UPDATE additional\n"
                        + "SET A_Cost='" + AddCost.getText() + "' WHERE 1";

                st.executeUpdate(query1);
                MealQ.setText(null);
                Amount.setText(null);
                ShopItemName.setText(null);

                AddItem.setText("Nothing");
                AddCost.setText("0");

            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_ShopSubmitMouseClicked

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void Name_MealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_MealActionPerformed

    }//GEN-LAST:event_Name_MealActionPerformed

    private void Name_MealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name_MealMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_MealMouseClicked

    private void MealQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealQActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddItemActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void MemberName_shopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberName_shopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberName_shopActionPerformed

    private void ShopItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShopItemNameActionPerformed

    private void AddCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCostActionPerformed

    private void Log_OutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseExited
        // TODO add your handling code here:
        indicator6.setBackground(new Color(255, 255, 255));
        Log_Out.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Log_OutMouseExited

    private void Log_OutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseEntered
        indicator6.setBackground(new Color(0, 0, 0));
        Log_Out.setBackground(new Color(247, 59, 63));
        //fina.setForeground(Color.white);
    }//GEN-LAST:event_Log_OutMouseEntered

    private void Log_OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_OutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Log Out From Your Account!", "Hey", 1);
        signIN.id = null;
        signIN s = new signIN();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Log_OutMouseClicked

    private void about1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about1MouseExited
        // TODO add your handling code here:
        indicator5.setBackground(new Color(255, 255, 255));
        about1.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_about1MouseExited

    private void about1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about1MouseEntered
        // TODO add your handling code here:
        indicator5.setBackground(new Color(0, 0, 0));
        about1.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_about1MouseEntered

    private void about1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about1MouseClicked
        About1 r1 = new About1();
        r1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_about1MouseClicked

    private void financesBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseExited
        // TODO add your handling code here:
//        indicator3.setBackground(new Color(255, 255, 255));
//        financesBox.setBackground(new Color(255, 255, 255));
        // fina.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_financesBoxMouseExited

    private void financesBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financesBoxMouseEntered
        // TODO add your handling code here:
//        indicator3.setBackground(new Color(0, 0, 0));
//        financesBox.setBackground(new Color(232, 232, 232));
        //fina.setForeground(new Color(1,122,232));
        // fina.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_financesBoxMouseEntered

    private void dashboardBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBoxMouseEntered
        // TODO add your handling code here:
        indicator2.setBackground(new Color(0, 0, 0));
        dashboardBox.setBackground(new Color(232, 232, 232));
    }//GEN-LAST:event_dashboardBoxMouseEntered

    private void dashboardBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBoxMouseExited
        // TODO add your handling code here:
        indicator2.setBackground(new Color(255, 255, 255));
        dashboardBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardBoxMouseExited

    private void updateComboboxMeal() {
        try {
            String query = "SELECT *, CONCAT(UserID, ' ', FirstName, ' ', LastName) AS FullName FROM userinfo";
            pst = conn.prepareStatement(query);

            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("FullName");
                Name_Meal.addItem(name);
                MemberName_shop.addItem(name);

            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddCost;
    private javax.swing.JTextField AddItem;
    private javax.swing.JTextField Amount;
    private javax.swing.JPanel Log_Out;
    private javax.swing.JTextField MealQ;
    private javax.swing.JLabel MealSubmit;
    private javax.swing.JComboBox<String> MemberName_shop;
    private javax.swing.JComboBox<String> Name_Meal;
    private javax.swing.JTextField ShopItemName;
    private javax.swing.JLabel ShopSubmit;
    private javax.swing.JLabel about;
    private javax.swing.JPanel about1;
    private javax.swing.JLabel calculate;
    private javax.swing.JLabel clearMeal;
    private javax.swing.JLabel clearShop;
    private javax.swing.JLabel dash;
    private javax.swing.JPanel dashboardBox;
    private javax.swing.JTextField date;
    private javax.swing.JLabel fina;
    private javax.swing.JPanel financesBox;
    private javax.swing.JPanel indicator2;
    private javax.swing.JPanel indicator3;
    private javax.swing.JPanel indicator5;
    private javax.swing.JPanel indicator6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel3;
    private javax.swing.JLabel report;
    // End of variables declaration//GEN-END:variables
}
